require "acts_as_active_storage_previewable/class_methods"
require "acts_as_active_storage_previewable/helpers"
require "acts_as_active_storage_previewable/railtie"
require "acts_as_active_storage_previewable/null_attachment"

module ActsAsActiveStoragePreviewable
end
